### ISSUE TITLE
Windows permission issues

### ISSUE THREAD

**Issue by wuubi** [obrien-k/orphic-cli#1]
Testing on Linux, but Windows gives template name error likely due to permissions failing on write (educated guess)

**Comment by obrien-k** [comment]
Another Windows-related error: https://stackoverflow.com/a/11889392/9281567

**Comment by obrien-k** [comment]
This could likely be fixed with correct permissions, but unsure of best permissions do use other than 600?

**Comment by obrien-k** [comment]
This is fine
